# Generated by Django 4.0.5 on 2022-06-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmgmt', '0002_prettynum_alter_userinfo_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], default=1, verbose_name='级别'),
        ),
    ]
